// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('activityindicator', 'Ti.UI.ActivityIndicator', {
  textProperty: undefined,
  factory: props => Ti.UI.createActivityIndicator(props)
});
