// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('button', 'Ti.UI.Button', {
  textProperty: 'title',
  factory: props => Ti.UI.createButton(props)
});
