// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('buttonbar', 'Ti.UI.ButtonBar', {
  textProperty: undefined,
  factory: props => Ti.UI.createButtonBar(props)
});
