// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('ios-ad', 'Ti.UI.iOS.AdView', {
  textProperty: undefined,
  factory: props => Ti.UI.iOS.createAdView(props)
});
