// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('label', 'Ti.UI.Label', {
  textProperty: 'text',
  factory: props => Ti.UI.createLabel(props)
});
