// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('maskedimage', 'Ti.UI.MaskedImage', {
  textProperty: undefined,
  factory: props => Ti.UI.createMaskedImage(props)
});
