// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('pickerrow', 'Ti.UI.PickerRow', {
  textProperty: undefined,
  factory: props => Ti.UI.createPickerRow(props)
});
