// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('progressbar', 'Ti.UI.ProgressBar', {
  textProperty: undefined,
  factory: props => Ti.UI.createProgressBar(props)
});
