// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('scroll', 'Ti.UI.ScrollView', {
  textProperty: undefined,
  factory: props => Ti.UI.createScrollView(props)
});
