// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('searchbar', 'Ti.UI.SearchBar', {
  textProperty: undefined,
  factory: props => Ti.UI.createSearchBar(props)
});
