// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('switch', 'Ti.UI.Switch', {
  textProperty: undefined,
  factory: props => Ti.UI.createSwitch(props)
});
