// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('tableviewrow', 'Ti.UI.TableViewRow', {
  textProperty: undefined,
  factory: props => Ti.UI.createTableViewRow(props)
});
