// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('tableviewsection', 'Ti.UI.TableViewSection', {
  textProperty: undefined,
  factory: props => Ti.UI.createTableViewSection(props)
});
