// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('textfield', 'Ti.UI.TextField', {
  textProperty: undefined,
  factory: props => Ti.UI.createTextField(props)
});
