// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('textarea', 'Ti.UI.TextArea', {
  textProperty: undefined,
  factory: props => Ti.UI.createTextArea(props)
});
