// Generated by scripts/generate-built-ins

import { register } from '../ReactTitaniumBridge';

register('webview', 'Ti.UI.WebView', {
  textProperty: undefined,
  factory: props => Ti.UI.createWebView(props)
});
